### ISSUE TITLE
Addon incompatibility and naming error

### ISSUE THREAD

**Issue by BiscuitCookies** [Road-block/ItemsOfPower#1]
The tooltips seem to disappear and give an error when SW_Stats is active>
Error is something like this
itemsofpower.lua on line 1164 attemp to call global 'select' (a nil value)
picture of complete error
http://puu.sh/tR8nE/ee878c7ffd.jpg

Also when naming new sets there should be no spaces in the name else the fubar items of power can't be used and it also can't be selected with in chat commands. It needs to be edited in the savedvariables to make it usable again.

Also how do I make it take base armor into caluclations and not bonus armor?

**Comment by Road-block** [comment]
EU time here so I'll take a look at these tomorrow.  
Thanks for report. (I thought I had caught all instances of select shim 😝 )

**Comment by BiscuitCookies** [comment]
Thanks for the fix and adding the base armor.
