### ISSUE TITLE
the tooltip display does not work on Nemesis Skullcap

### ISSUE THREAD

**Issue by Krabator** [Road-block/ItemsOfPower#2]
Hello,

The addon works fine but it does not display my value on this item.
Not sure if it's a bug or a problem of text size...

**Comment by Road-block** [comment]
Can you give some more info?   
- What kind of stats are you giving values to?
- Are you playing on English client or another language?  

That would help me see if it's a problem with the item parser or something else.

**Comment by Road-block** [comment]
Closing this as it was an item broken on Elysium, nothing to do with the addon itself.
